version: "3"
services:
  mysqldb:
    container_name: mysql_db
    platform: linux/x86_64
    image: mysql:8.0.26
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: hbooking
      MYSQL_DATABASE: hbooking
      MYSQL_USER: hbooking
      MYSQL_PASSWORD: hbooking
  hbooking:
    container_name: hbooking
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        IMAGE_NAME: golang:1.21.6-alpine
        APP_NAME: hbooking
        SERVICE: hbooking
        PORT: 8888
    volumes:
      - ./:/hbooking
    ports:
      - 8888:8888
    links:
      - mysqldb:mysqldb
    depends_on:
      - mysqldb
